### ISSUE TITLE
cv_container - port definition is not working

### ISSUE THREAD

**Issue by titom73** [Hugh-Adams/CVP_Ansible_Modules#5]
When trying to configure CVP port in module, following error raises:

```shell
('https://%s:%d/web' % (host, self.port or 443))\nTypeError: %d format: a number is required, not list\n"
```

__Ansible version__

_Version:_ `2.8.3`

```shell
ansible 2.8.3
  config file = /Users/tgrimonet/Projects/01-github/ansible-cvp-module/examples/ansible.cfg
  configured module search path = [u'/Users/tgrimonet/Projects/01-github/ansible-cvp-module/module', u'/Users/tgrimonet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tgrimonet/Projects/01-github/ansible-cvp-module/.venv/lib/python2.7/site-packages/ansible
  executable location = /Users/tgrimonet/Projects/01-github/ansible-cvp-module/.venv/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

__Python Version__

_Version:_ `2.7.10`

```shell
python --version
Python 2.7.10
```

__Full stack log__

- Playbook:

```yaml
---
- name: Test cv_container
  hosts: cvp
  connection: local
  gather_facts: no
  tasks:
    - name: Create a container on CVP.
      cv_container:
        host: '{{ansible_host}}'
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        protocol: https
        port: 443
        container: ansible_container
        parent: Tenant
        action: add
```

- Output logs:

```
ansible-playbook playbook.configlet.yaml -i inventory.ini

PLAY [Test cv_container] ****************************************************************************************************************************************************************************************************************

TASK [Create a container on CVP.] *******************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: %d format: a number is required, not list
fatal: [cvp_server]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/tgrimonet/.ansible/tmp/ansible-tmp-1565705054.83-102695675559209/AnsiballZ_cv_container.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/tgrimonet/.ansible/tmp/ansible-tmp-1565705054.83-102695675559209/AnsiballZ_cv_container.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/tgrimonet/.ansible/tmp/ansible-tmp-1565705054.83-102695675559209/AnsiballZ_cv_container.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/bj/x0pdlg4s46vbk9t8916xkfb00000gn/T/ansible_cv_container_payload_yqZZyY/__main__.py\", line 183, in <module>\n  File \"/var/folders/bj/x0pdlg4s46vbk9t8916xkfb00000gn/T/ansible_cv_container_payload_yqZZyY/__main__.py\", line 164, in main\n  File \"/var/folders/bj/x0pdlg4s46vbk9t8916xkfb00000gn/T/ansible_cv_container_payload_yqZZyY/__main__.py\", line 101, in connect\n  File \"/Users/tgrimonet/Projects/01-github/ansible-cvp-module/.venv/lib/python2.7/site-packages/cvprac/cvp_client.py\", line 265, in connect\n    self._create_session(all_nodes=True)\n  File \"/Users/tgrimonet/Projects/01-github/ansible-cvp-module/.venv/lib/python2.7/site-packages/cvprac/cvp_client.py\", line 283, in _create_session\n    self.url_prefix = ('https://%s:%d/web' % (host, self.port or 443))\nTypeError: %d format: a number is required, not list\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
cvp_server                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by titom73** [comment]
Module arguments uses a list as input for port:

```python
argument_spec = dict(
        host=dict(required=True),
        port=dict(type='list', default=None),
		[...]
    )
```

But `cvprac` expect a `int` as port definition:

```python
def connect(self, nodes, username, password, connect_timeout=10,
            protocol='https', port=None, cert=False):
    ''' Login to CVP and get a session ID and cookie.  Currently
        certificates are not verified if the https protocol is specified. A
        warning may be printed out from the requests module for this case.

        Args:
            [...]
            port (int): The TCP port of the endpoint for the connection.
                If this keyword is not specified, the default value is
                automatically determined by the transport type.
                (http=80, https=443)
    '''
    [...]
```

And __`cv_*`__ modules just use port input as is with no conversion to `int`:

```python
def connect(module):
    client = CvpClient()
    try:
        client.connect([module.params['host']],
                       module.params['username'],
                       module.params['password'],
                       protocol=module.params['protocol'],
                       port=module.params['port'],
                       )
    except CvpLoginError, e:
        module.fail_json(msg=str(e))

    return client
```

**Comment by titom73** [comment]
Changing port type in module argument from `list` to `int` allow to define custom port:

```diff
     argument_spec = dict(
         host=dict(required=True),
-        port=dict(type='list', default=None),
+        port=dict(type='int', default=None),
         protocol=dict(default='https', choices=['http', 'https']),
         username=dict(required=True),
         password=dict(required=True, no_log=True),
```

__Playbook example__

```yaml
---
- name: Test cv_container
  hosts: cvp
  connection: local
  gather_facts: no
  vars:
    - container_name: issue05
    - container_parent: Tenant
  tasks:
    - name: Create a container on CVP.
      cv_container:
        host: '{{ansible_host}}'
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        protocol: https
        port: 443
        container: "{{container_name}}"
        parent: "{{container_parent}}"
        action: add
```

__Playbook result__

```shell
(.venv) tests|master⚡ ⇒ ansible-playbook playbook.issue05.port.yml

PLAY [Test cv_container] ******

TASK [Create a container on CVP.] ******
changed: [cvp_server]

PLAY RECAP ******
cvp_server                 : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
