### ISSUE TITLE
cv_configlet - Template is not rendered in configlet

### ISSUE THREAD

**Issue by titom73** [Hugh-Adams/CVP_Ansible_Modules#8]
When using a template to generate a configlet, `cv_configlet` is not loading content from data file:

__Ansible task__

```
---
- name: Test cv_container
  hosts: cvp
  connection: local
  gather_facts: no
  vars:
    - container_name: automated_container
    - container_parent: Tenant
    - configlet_name: ansible_configlet
    - configlet_template: "configlet.template.j2"
    - configlet_data: "templates/cvp.yml"
  tasks:
    # Create configlet attached to container
    - name: Create a configlet on CVP.
      cv_configlet:
        host: '{{ansible_host}}'
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        protocol: https
        container: "{{container_name}}"
        parent: "{{container_parent}}"
        configletName: "{{configlet_name}}"
        template: "{{configlet_template}}"
        data: "{{configlet_data}}"
        action: add
      ignore_errors: yes
```

__YAML file for data__

```
---
hostname: "test"
```

__Error Message__

```shell
fatal: [cvp_server]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "add",
            "configletConfig": "None",
            "configletName": "ansible_configlet",
            "container": "automated_container",
            "data": "{'hostname': 'test'}",
            "device": "None",
            "host": "10.73.1.139",
            "parent": "Tenant",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "protocol": "https",
            "template": "configlet.template.j2",
            "username": "tom"
        }
    },
    "msg": "Template configlet.template.j2 requires hostname value"
}
```

__Ansible version__

_Version:_ `2.8.3`

```shell
ansible 2.8.3
  config file = /Users/tgrimonet/Projects/01-github/ansible-cvp-module/examples/ansible.cfg
  configured module search path = [u'/Users/tgrimonet/Projects/01-github/ansible-cvp-module/module', u'/Users/tgrimonet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tgrimonet/Projects/01-github/ansible-cvp-module/.venv/lib/python2.7/site-packages/ansible
  executable location = /Users/tgrimonet/Projects/01-github/ansible-cvp-module/.venv/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

__Python Version__

_Version:_ `2.7.10`

```shell
python --version
Python 2.7.10
```
