### ISSUE TITLE
cv_device - Device not found even if present on CVP

### ISSUE THREAD

**Issue by titom73** [Hugh-Adams/CVP_Ansible_Modules#9]
`cv_device` is not able to find device on CVP regardless its container.

Original Ansible Output example:
```
TASK [Display cv_device add result] ***
ok: [cvp_server] => {
    "msg": {
        "changed": false, 
        "data": {
            "error": "No Device Found: veos-cvp"
        }, 
        "failed": false
    }
}
```

Playbook applied:

```yaml
- name: Show device information from CVP
  cv_device:
    host: '{{ansible_host}}'
    username: '{{cvp_username}}'
    password: '{{cvp_password}}'
    protocol: https
    device: "{{cvp_device}}"
    container: "ansible-fabric"
    action: show
  register: cvp_result

- name: Display cv_device add result
  debug:
    msg: "{{cvp_result}}"
```

If we do a REST call, we can find the device and the same if we insert a `module.fail_json(msg=str('Debug - device_info: %r' %device_info))` at line 127, we can see device is correctly sent by CVP

```
fatal: [cvp_server]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "show",
            "configlet": [
                "None"
            ],
            "container": "********-fabric",
            "device": "veos-cvp",
            "host": "10.83.28.164",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "protocol": "https",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Debug - device_info: {'memTotal': 0, u'version': u'4.22.0F', u'internalVersion': u'4.22.0F', 'dcaKey': None, u'systemMacAddress': u'50:00:00:ae:f7:03', 'tempAction': None, 'deviceStatus': u'Registered', 'taskIdList': [], 'internalBuildId': u'2c34e816-9aa7-4c63-9a32-05140aec7dbd', u'mlagEnabled': False, u'modelName': u'vEOS', u'hostname': u'veos-cvp', u'complianceCode': u'', u'danzEnabled': False, 'type': 'netelement', 'isDANZEnabled': False, 'parentContainerId': u'container_2_438231636086202', u'status': u'Registered', u'unAuthorized': False, u'parentContainerKey': u'container_2_438231636086202', 'deviceInfo': u'Registered', u'ztpMode': True, u'bootupTimestamp': 1566229532.8599389, 'lastSyncUp': 0, 'key': u'50:00:00:ae:f7:03', 'containerName': u'Ansible Fabric', 'sslConfigAvailable': False, u'domainName': u'', u'internalBuild': u'2c34e816-9aa7-4c63-9a32-05140aec7dbd', 'sslEnabledByCVP': False, u'serialNumber': u'DD4CA16C87FE74DB7D77FB88374687FB', u'fqdn': u'veos-cvp', 'bootupTimeStamp': 1566229532.8599389, 'isMLAGEnabled': False, u'streamingStatus': u'active', 'memFree': 0, u'architecture': u'', u'hardwareRevision': u'', u'ipAddress': u'10.255.0.20', u'complianceIndication': u''}"
}
```
